### ISSUE TITLE
[backend_fs] externally deleting a glyph does not work with the change watcher

### ISSUE THREAD

**Issue by justvanrossum** [BlackFoundryCom/fontra-rcjk#37]
Error:
```
2023-01-27 11:07:18 fontra.core.fonthandler ERROR    fatal exception in asyncio task <Task finished name='Task-111' coro=<FontHandler.processExternalChanges() done, defined at /Users/just/code/git/BlackFoundry/fontra/src/fontra/core/fonthandler.py:86> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/Users/just/code/git/BlackFoundry/fontra/src/fontra/core/fonthandler.py", line 87, in processExternalChanges
    async for change, reloadPattern in self.backend.watchExternalChanges():
  File "/Users/just/code/git/BlackFoundry/fontra-rcjk/src/fontra_rcjk/backend_fs.py", line 150, in watchExternalChanges
    if self._recentlyWrittenPaths.pop(path, None) == os.path.getmtime(path):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/project.rcjk/characterGlyph/a.glif'
```
This may be a combination of two things
- The code itself is buggy
- The watchfiles oddity worked around in the ds backend here: https://github.com/googlefonts/fontra/commit/063923fb4f319dff89236c5009ddeda2c7c8faff

The watchfiles oddity probably deserves a wrapper, so that watchfiles client code doesn't need to worry about it.

**Comment by justvanrossum** [comment]
Externally adding a glyph also doesn't seem to work.
